### ISSUE TITLE
OpenSSL 1.1.1d

### ISSUE THREAD

**Issue by zc0nf** [flakes/mirc_fish_10#53] opened 2018-08-26 16:04 UTC
Hello!

Can you update to latest openssl version?

Thx,

zc0nf

**Comment by zc0nf** [comment] 2019-10-05 23:32
Now OpenSSL 1.1.1d :-)

**Comment by flakes** [comment] 2019-10-06 14:05
Working on it, lots of API changes. Closing this ticket as it's basically a duplicate of #57.

**Closed** 2019-10-06 14:06 UTC
